from .dramabox_tts import NODE_CLASS_MAPPINGS as _TTS_CLS, NODE_DISPLAY_NAME_MAPPINGS as _TTS_DISP
from .dramabox_options import NODE_CLASS_MAPPINGS as _OPT_CLS, NODE_DISPLAY_NAME_MAPPINGS as _OPT_DISP
from .dramabox_clip import NODE_CLASS_MAPPINGS as _CLIP_CLS, NODE_DISPLAY_NAME_MAPPINGS as _CLIP_DISP

NODE_CLASS_MAPPINGS = {**_TTS_CLS, **_OPT_CLS, **_CLIP_CLS}
NODE_DISPLAY_NAME_MAPPINGS = {**_TTS_DISP, **_OPT_DISP, **_CLIP_DISP}
